travis:
  secure:
    BINSTAR_TOKEN: Xr5wpEQVzZnclVggs1CFuSMG94wvZqcoMOrmoYNPm634MLHNYjP+kSoU7sOYEDGOcl0g1zDK6OTB3cTyDLBcOudWD+NGJHFQw3lzisUymooAxpbSvD77WjR2ozi8+w/YRyI+RuVdkJ6yMjGJ0lHGr1FC/gYU7z3EGkVRud+z1Vhz5kklRwKT5PnJ91UwSUZtP/BvtOzx4vqrIC2Xi+RNqxdAS6EkT5zO1CJH0J9N86NGLrxdg1RqicDh+57Uy8aMOJedxb7OXB2+xcLVh3FTGnKVIQZOvtVCbMLSBF2k8r3VFbs4ZRk7IV4MrrjwyTVswnRFRTLP1xmqW10k3lSNK89UTX0ILp2tbkXoCSC/G7yfJldPbB6XbOXJP5FMRd3wGR8JnhUsHTV2P8vto4k3cdzqf/pKrWA+tnrSEtQ06TqJZ1rvp1M9fx8yBILwUMr5VuUzjmXRRm7zKjOKMnhj/Yj6STZvc6C6KjQdYY0CnfgGgMxZbRWzC8l1dPskRHypVvncHC4z3fKR9x0Cc9MX1K0G+k9yJRj01S145+5WnhVg0cT2x3r+ChhaGm5E2t2MaN/uwuQk70k1wtTmm4dzOi36AWx79okOlGDEg3xn4EQEwe795Hcpg4012g81twRdcGqE+V+nVmHMgTSMfcB/0Dca0A7Hy8bn4aVnSCOPBWY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
